name: Build, Analyze, and Scans
on:
  push:
    branches:
      - main
jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: windows-latest
    steps:
     - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

     - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Docker build and push
        run: |
          # Run commands to build and push Docker images
          docker build -t  .
          docker tag  11681515/:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push 11681515/:latest

     - name: Docker Scout Image Scan
        run: |
          docker quickview 11681515/:latest
          docker cves 11681515/:latest
